"""Create weekly market prices table

Revision ID: 2064d385b002
Revises: 340242565331
Create Date: 2026-08-24 15:55:28.356439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2064d385b002'
down_revision: Union[str, Sequence[str], None] = '340242565331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_weekly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('market_name', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('average_price_per_quintal', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('previous_week_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('previous_month_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('previous_year_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('change_over_previous_week_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('change_over_previous_month_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('change_over_previous_year_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'market_name', 'week_start', name='unique_weekly_market_crop')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_price_weekly')
    # ### end Alembic commands ###
