"""Create market prices table

Revision ID: 340242565331
Revises: 81df5eeff2b4
Create Date: 2026-08-24 13:30:48.007985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340242565331'
down_revision: Union[str, Sequence[str], None] = '81df5eeff2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('market_name', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('min_price_per_quintal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_price_per_quintal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('modal_price_per_quintal', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('arrival_quantity_quintals', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'market_name', 'price_date', name='unique_market_crop_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_prices')
    # ### end Alembic commands ###
