"""Create weather table

Revision ID: 81df5eeff2b4
Revises: f06277ab3b98
Create Date: 2026-08-24 13:28:43.914832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81df5eeff2b4'
down_revision: Union[str, Sequence[str], None] = 'f06277ab3b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('taluk', sa.String(length=50), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('temp_max_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temp_min_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district', 'taluk', 'record_date', name='unique_weather_day_location')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
