"""Create crops table

Revision ID: f06277ab3b98
Revises: 21828f1acf38
Create Date: 2026-08-24 13:24:44.404752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f06277ab3b98'
down_revision: Union[str, Sequence[str], None] = '21828f1acf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tamil_name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('growing_days_min', sa.Integer(), nullable=False),
    sa.Column('growing_days_max', sa.Integer(), nullable=False),
    sa.Column('min_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('max_temp_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('min_rainfall_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('max_rainfall_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('water_requirement_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('soil_compatibility', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crops')
    # ### end Alembic commands ###
